backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "jobs"
    label: "Jobs"
    folder: "src/pages/jobs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "job-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Company Logo", name: "logo", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}

  - name: "certs"
    label: "Certs"
    folder: "src/pages/certs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cert-post"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "School Logo", name: "logo", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}

  - name: "project"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Technology Used 1", name: "tech_1", widget: "image"}
      - {label: "Technology Used 2", name: "tech_2", widget: "image"}
      - {label: "Technology Used 3", name: "tech_3", widget: "image"}


  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields: 
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: "Heading", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Featured Image", name: "featuredImage", widget: "image"}
          - {label: "biline", name: "biline", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "download", name: "download", widget: "string"}
          - {label: "Github", name: "github", widget: "string"}
          - {label: "Twitter", name: "twitter", widget: "string"}
          - {label: "Linkedin", name: "linkedin", widget: "string"}
          - {label: "Medium", name: "medium", widget: "string"}